server:
  port: 8081
  context-path: /demo


name: yiyi
age: 18

user:
  username: yiyi
  age: 18

spring:
  datasource:
    url: jdbc:mysql://10.11.31.239:3306/demo?characterEncoding=utf8&useSSL=true
#    url: jdbc:mysql://192.168.1.200:3306/demo?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gss@MFD*4299
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  messages:
    basename: i18n.messages






