server:
  port: 8088
  context-path: /demo


name: yiyi
age: 18

user:
  username: yiyi
  age: 18

spring:
  datasource:
    url: jdbc:mysql://db201.dev.rs.com:3306/db_digital?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true





